# Generated by Django 2.2.5 on 2020-01-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_auto_20200129_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
